// Mocks generated by Mockito 5.4.4 from annotations
// in expense_tracker/test/providers/app_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:expense_tracker/models/auth_models.dart' as _i3;
import 'package:expense_tracker/models/expenditure_item.dart' as _i7;
import 'package:expense_tracker/models/income_item.dart' as _i6;
import 'package:expense_tracker/network/services/apiservice.dart' as _i4;
import 'package:http_interceptor/http/intercepted_client.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInterceptedClient_0 extends _i1.SmartFake
    implements _i2.InterceptedClient {
  _FakeInterceptedClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoginResponse_1 extends _i1.SmartFake implements _i3.LoginResponse {
  _FakeLoginResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignupResponse_2 extends _i1.SmartFake
    implements _i3.SignupResponse {
  _FakeSignupResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserProfile_3 extends _i1.SmartFake implements _i3.UserProfile {
  _FakeUserProfile_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i4.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.InterceptedClient get httpClient => (super.noSuchMethod(
        Invocation.getter(#httpClient),
        returnValue: _FakeInterceptedClient_0(
          this,
          Invocation.getter(#httpClient),
        ),
      ) as _i2.InterceptedClient);

  @override
  _i5.Future<_i3.LoginResponse> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i5.Future<_i3.LoginResponse>.value(_FakeLoginResponse_1(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i5.Future<_i3.LoginResponse>);

  @override
  _i5.Future<_i3.SignupResponse> signup(
    String? name,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signup,
          [
            name,
            email,
            password,
          ],
        ),
        returnValue: _i5.Future<_i3.SignupResponse>.value(_FakeSignupResponse_2(
          this,
          Invocation.method(
            #signup,
            [
              name,
              email,
              password,
            ],
          ),
        )),
      ) as _i5.Future<_i3.SignupResponse>);

  @override
  _i5.Future<List<_i6.IncomeItem>> getIncome() => (super.noSuchMethod(
        Invocation.method(
          #getIncome,
          [],
        ),
        returnValue: _i5.Future<List<_i6.IncomeItem>>.value(<_i6.IncomeItem>[]),
      ) as _i5.Future<List<_i6.IncomeItem>>);

  @override
  _i5.Future<List<_i7.ExpenditureItem>> getExpenditure() => (super.noSuchMethod(
        Invocation.method(
          #getExpenditure,
          [],
        ),
        returnValue: _i5.Future<List<_i7.ExpenditureItem>>.value(
            <_i7.ExpenditureItem>[]),
      ) as _i5.Future<List<_i7.ExpenditureItem>>);

  @override
  _i5.Future<String> addIncome(
    String? name,
    String? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addIncome,
          [
            name,
            amount,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #addIncome,
            [
              name,
              amount,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> addExpense(
    String? name,
    String? category,
    int? categoryId,
    String? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addExpense,
          [
            name,
            category,
            categoryId,
            amount,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.UserProfile> getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _i5.Future<_i3.UserProfile>.value(_FakeUserProfile_3(
          this,
          Invocation.method(
            #getUserProfile,
            [],
          ),
        )),
      ) as _i5.Future<_i3.UserProfile>);
}
