// Mocks generated by Mockito 5.4.4 from annotations
// in expense_tracker/test/screens/home/expenses_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i8;

import 'package:expense_tracker/models/auth_models.dart' as _i2;
import 'package:expense_tracker/models/expenditure_item.dart' as _i5;
import 'package:expense_tracker/models/income_item.dart' as _i4;
import 'package:expense_tracker/providers/app_provider.dart' as _i3;
import 'package:flutter/material.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserProfile_0 extends _i1.SmartFake implements _i2.UserProfile {
  _FakeUserProfile_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AppProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppProvider extends _i1.Mock implements _i3.AppProvider {
  MockAppProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  List<_i4.IncomeItem> get incomeItems => (super.noSuchMethod(
        Invocation.getter(#incomeItems),
        returnValue: <_i4.IncomeItem>[],
      ) as List<_i4.IncomeItem>);

  @override
  List<_i5.ExpenditureItem> get expenditureItems => (super.noSuchMethod(
        Invocation.getter(#expenditureItems),
        returnValue: <_i5.ExpenditureItem>[],
      ) as List<_i5.ExpenditureItem>);

  @override
  _i2.UserProfile get userProfile => (super.noSuchMethod(
        Invocation.getter(#userProfile),
        returnValue: _FakeUserProfile_0(
          this,
          Invocation.getter(#userProfile),
        ),
      ) as _i2.UserProfile);

  @override
  double get totalIncome => (super.noSuchMethod(
        Invocation.getter(#totalIncome),
        returnValue: 0.0,
      ) as double);

  @override
  double get totalExpenditure => (super.noSuchMethod(
        Invocation.getter(#totalExpenditure),
        returnValue: 0.0,
      ) as double);

  @override
  double get balance => (super.noSuchMethod(
        Invocation.getter(#balance),
        returnValue: 0.0,
      ) as double);

  @override
  _i6.ThemeMode get themeMode => (super.noSuchMethod(
        Invocation.getter(#themeMode),
        returnValue: _i6.ThemeMode.system,
      ) as _i6.ThemeMode);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setTokenForTesting(String? token) => super.noSuchMethod(
        Invocation.method(
          #setTokenForTesting,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> signup(
    String? name,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signup,
          [
            name,
            email,
            password,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> loadToken() => (super.noSuchMethod(
        Invocation.method(
          #loadToken,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> fetchIncome() => (super.noSuchMethod(
        Invocation.method(
          #fetchIncome,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> fetchExpenditure() => (super.noSuchMethod(
        Invocation.method(
          #fetchExpenditure,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> fetchAllFinanceData() => (super.noSuchMethod(
        Invocation.method(
          #fetchAllFinanceData,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void clearFinanceData() => super.noSuchMethod(
        Invocation.method(
          #clearFinanceData,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> initializeApp() => (super.noSuchMethod(
        Invocation.method(
          #initializeApp,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> addIncome(
    String? name,
    double? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addIncome,
          [
            name,
            amount,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> addExpense(
    String? name,
    String? category,
    double? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addExpense,
          [
            name,
            category,
            amount,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setThemeMode(_i6.ThemeMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [mode],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> loadThemeMode() => (super.noSuchMethod(
        Invocation.method(
          #loadThemeMode,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
